"""changes to feedback

Revision ID: 42a17d8c1b31
Revises: 336b42cd86ce
Create Date: 2024-05-11 17:28:06.738798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42a17d8c1b31'
down_revision = '336b42cd86ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.String(), nullable=True))
        batch_op.drop_column('message')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
