"""insta fields in offers

Revision ID: 66e91537c3c2
Revises: 0b35efa8471a
Create Date: 2024-05-16 18:57:10.541077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66e91537c3c2'
down_revision = '0b35efa8471a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('insta_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_column('insta_url')

    # ### end Alembic commands ###
